// Package skill ships the Claude Code authoring skill inside the slides binary and
// installs it into a workspace's .claude/skills/ directory.
//
// # Why the binary carries its own skill
//
// SKILL.md and AUTHORING.md are re-encodings of the data-* layout contract — alongside
// the editor's layout.ts, the CLI's validate.go, the runtime slides-layout-init.js, and
// the thumbnail's static port.  A copy that drifts teaches Claude Code rules the
// validator no longer enforces, which is worse than no skill at all: the deck looks
// authored correctly and then fails `slides validate`.
//
// A workspace is usually a *separate repo* from the slides-builder source tree (spec
// project-structure), so the skill has to reach it somehow, and hand-copying forks the
// contract.  The binary is therefore the carrier, exactly as it already carries reveal.js
// and the layout assets, with the same guarantee:
//
//	The contract the skill teaches always matches the binary that validates it.
//
// The source of truth is assets/slides-authoring/, versioned in this repo next to
// validate.go and layout.ts, so a change to the vocabulary updates the validator and the
// skill in one commit.  Everything written to a workspace is a generated artifact and
// carries a header saying so.
package skill

import (
	"bytes"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// assets holds the canonical skill sources.  go:embed cannot reach outside the package
// directory, which is precisely why these files live here rather than in docs/ or a
// top-level .claude/ — there is exactly one copy, and it is the one compiled into the
// binary.
//
//go:embed assets/slides-authoring
var assets embed.FS

const (
	// srcDir is the embedded path prefix.
	srcDir = "assets/slides-authoring"

	// Name is the skill's directory name, matching the `name:` in its frontmatter.
	Name = "slides-authoring"

	// InstallDir is the workspace-relative directory the skill is installed into.
	// Claude Code discovers skills here.
	InstallDir = ".claude/skills/" + Name
)

// header is stamped into every installed file.  It is an HTML comment so it renders as
// nothing in Markdown but is plainly visible to whoever (or whatever) opens the file.
//
// It names the source path rather than just saying "do not edit", because the failure it
// prevents is silent: an author who edits the installed copy forks the contract, and the
// only symptom is a deck that looks right and fails validation.
const header = `<!-- GENERATED by ` + "`slides install-skill`" + ` — do not edit.
     Source of truth: internal/skill/assets/slides-authoring/ in the slides-builder repo,
     versioned alongside internal/validate/validate.go and web/src/lib/model/layout.ts.
     Editing this copy forks the data-* contract: decks authored against a stale skill
     look correct and then fail ` + "`slides validate`" + `. Re-run ` + "`slides install-skill`" + ` to refresh. -->
`

// Result reports what an Install did.  Written lists the workspace-relative paths whose
// bytes changed; an empty slice means the install was a no-op.
type Result struct {
	Dir     string   // absolute path of the installed skill directory
	Written []string // files whose contents changed (empty on a re-install)
	Total   int      // files the skill comprises
}

// Changed reports whether Install altered anything on disk.
func (r Result) Changed() bool { return len(r.Written) > 0 }

// Install writes the embedded skill into <root>/.claude/skills/slides-authoring/.
//
// It is idempotent and byte-stable, like deck.Vendor: re-installing an unchanged skill
// leaves every file untouched (it compares bytes and skips the write, so mtimes stay put
// and a decks repo that commits the skill sees no spurious diff).  A file that was edited
// or deleted is restored to the canonical bytes — the point is convergence on the
// contract the binary enforces, not preservation of local edits.
//
// root must already be a resolved workspace; Install creates only the skill directory.
func Install(root string) (Result, error) {
	dest := filepath.Join(root, filepath.FromSlash(InstallDir))
	res := Result{Dir: dest}

	files, err := Files()
	if err != nil {
		return res, err
	}
	res.Total = len(files)

	if err := os.MkdirAll(dest, 0o755); err != nil {
		return res, fmt.Errorf("mkdir %s: %w", dest, err)
	}

	for _, name := range files {
		want, err := Render(name)
		if err != nil {
			return res, err
		}
		target := filepath.Join(dest, name)

		got, err := os.ReadFile(target)
		switch {
		case err == nil && bytes.Equal(got, want):
			continue // already current — skip the write so re-installing is a true no-op.
		case err != nil && !errors.Is(err, os.ErrNotExist):
			return res, fmt.Errorf("read %s: %w", target, err)
		}

		if err := os.WriteFile(target, want, 0o644); err != nil {
			return res, fmt.Errorf("write %s: %w", target, err)
		}
		res.Written = append(res.Written, filepath.Join(InstallDir, name))
	}
	return res, nil
}

// Files returns the skill's file names (no directory component), sorted, as embedded.
func Files() ([]string, error) {
	entries, err := fs.ReadDir(assets, srcDir)
	if err != nil {
		return nil, fmt.Errorf("read embedded skill: %w", err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			names = append(names, e.Name())
		}
	}
	return names, nil // fs.ReadDir already sorts by filename.
}

// Render returns the installable bytes of one skill file: the embedded source with the
// generated header stamped in.
func Render(name string) ([]byte, error) {
	src, err := assets.ReadFile(srcDir + "/" + name)
	if err != nil {
		return nil, fmt.Errorf("read embedded %s: %w", name, err)
	}
	return stamp(src), nil
}

// frontmatterFence delimits the YAML frontmatter Claude Code reads to discover a skill.
var frontmatterFence = []byte("---\n")

// stamp inserts the generated header into src.
//
// A skill's YAML frontmatter must begin at byte 0 or Claude Code will not recognise the
// file, so the header cannot simply be prepended: when frontmatter is present the header
// goes immediately after its closing fence, otherwise at the top.
func stamp(src []byte) []byte {
	var out bytes.Buffer

	body := src
	if bytes.HasPrefix(src, frontmatterFence) {
		rest := src[len(frontmatterFence):]
		if i := bytes.Index(rest, []byte("\n"+string(frontmatterFence))); i >= 0 {
			end := len(frontmatterFence) + i + 1 + len(frontmatterFence)
			out.Write(src[:end])
			out.WriteString("\n")
			body = src[end:]
		}
	}
	out.WriteString(header)
	// body starts with the blank line that followed the fence (or is the whole file).
	if !bytes.HasPrefix(body, []byte("\n")) {
		out.WriteString("\n")
	}
	out.Write(body)
	return out.Bytes()
}
