/**
 * slides.test.ts — Pure slide-management model ops (P6, spec 06).
 *
 * Verifies correctness of add / duplicate / delete / move / nest / promote / hide
 * AND the byte-stable round-trip invariant (spec 12 #4): every untouched sibling
 * slide serializes verbatim after an operation.
 */

import { describe, it, expect } from 'vitest';
import { parseDeck, serializeDeck, stampEids, getAttribute } from '$lib/model';
import {
  addSlide,
  duplicateSlide,
  deleteSlide,
  moveSlide,
  moveVerticalSlide,
  nestSlide,
  promoteSlide,
  setSlideHidden,
  topLevelSlides,
  verticalChildren,
  isVerticalStack,
  buildSlideTree,
} from './slides';
import { buildThumbnailSrcdoc } from './thumbnail';

// Single-line slides keep substring byte-stability checks trivial. Whitespace
// between sections is a single '\n'.
const DECK = `<!doctype html>
<html>
<body>
<div class="reveal">
<div class="slides">
<section data-eid="s1" data-id="a"><h1>One</h1></section>
<section data-eid="s2"><h2>Two</h2></section>
<section data-eid="s3"><section data-eid="s3a"><p>3a</p></section><section data-eid="s3b"><p>3b</p></section></section>
</div>
</div>
</body>
</html>`;

const S1 = '<section data-eid="s1" data-id="a"><h1>One</h1></section>';
const S2 = '<section data-eid="s2"><h2>Two</h2></section>';
const S3 =
  '<section data-eid="s3"><section data-eid="s3a"><p>3a</p></section><section data-eid="s3b"><p>3b</p></section></section>';

/** Order of element eids inside the output, by source position. */
function eidOrder(html: string, eids: string[]): string[] {
  return [...eids]
    .map((eid) => ({ eid, at: html.indexOf(`data-eid="${eid}"`) }))
    .filter((e) => e.at >= 0)
    .sort((a, b) => a.at - b.at)
    .map((e) => e.eid);
}

describe('fixture sanity', () => {
  it('round-trips byte-for-byte unedited', () => {
    expect(serializeDeck(parseDeck(DECK))).toBe(DECK);
  });

  it('buildSlideTree reflects the 2D structure', () => {
    const tree = buildSlideTree(parseDeck(DECK));
    expect(tree.map((t) => t.eid)).toEqual(['s1', 's2', 's3']);
    expect(tree[0].verticals).toHaveLength(0);
    expect(tree[2].verticals.map((v) => v.eid)).toEqual(['s3a', 's3b']);
    expect(tree[2].hidden).toBe(false);
  });
});

describe('addSlide (P6-3)', () => {
  it('appends a starter section and leaves siblings byte-stable', () => {
    const model = parseDeck(DECK);
    const section = addSlide(model);
    expect(section).not.toBeNull();
    expect(getAttribute(section!, 'data-lay')).toBe('stack');
    const out = serializeDeck(model);
    expect(out).toContain('<section data-lay="stack"><h2>New slide</h2></section>');
    // Untouched slides serialize verbatim.
    expect(out).toContain(S1);
    expect(out).toContain(S2);
    expect(out).toContain(S3);
    // New slide is last.
    expect(topLevelSlides(model)).toHaveLength(4);
  });

  it('inserts after the given slide', () => {
    const model = parseDeck(DECK);
    addSlide(model, 's1');
    const out = serializeDeck(model);
    // New (unstamped) section lands between s1 and s2.
    const at1 = out.indexOf('data-eid="s1"');
    const atNew = out.indexOf('data-lay="stack"');
    const at2 = out.indexOf('data-eid="s2"');
    expect(at1).toBeLessThan(atNew);
    expect(atNew).toBeLessThan(at2);
  });

  it('returns null when there is no slides container', () => {
    const model = parseDeck('<div><p>no reveal here</p></div>');
    expect(addSlide(model)).toBeNull();
  });
});

describe('duplicateSlide (P6-3 / spec 07 pairing)', () => {
  it('clones after the original, strips data-eid, preserves data-id', () => {
    const model = parseDeck(DECK);
    const clone = duplicateSlide(model, 's1');
    expect(clone).not.toBeNull();
    // The clone has NO data-eid yet (regenerated by the caller's stampEids)…
    expect(getAttribute(clone!, 'data-eid')).toBeNull();
    // …but keeps data-id so reveal auto-animate can pair the two slides.
    expect(getAttribute(clone!, 'data-id')).toBe('a');

    const out = serializeDeck(model);
    expect(out).toContain('<section data-id="a"><h1>One</h1></section>'); // the copy
    expect(out).toContain(S1); // original untouched
    expect(out).toContain(S2);
  });

  it('regenerates a unique eid after stampEids', () => {
    const model = parseDeck(DECK);
    const clone = duplicateSlide(model, 's1')!;
    stampEids(model);
    const eid = getAttribute(clone, 'data-eid');
    expect(eid).not.toBeNull();
    expect(['s1', 's2', 's3', 's3a', 's3b']).not.toContain(eid);
  });

  it('duplicates a vertical slide in place', () => {
    const model = parseDeck(DECK);
    const clone = duplicateSlide(model, 's3a');
    expect(clone).not.toBeNull();
    // Copy sits inside the stack, right after s3a.
    expect(verticalChildren(topLevelSlides(model)[2])).toHaveLength(3);
  });
});

describe('deleteSlide (P6-3)', () => {
  it('removes the slide and keeps siblings byte-stable', () => {
    const model = parseDeck(DECK);
    expect(deleteSlide(model, 's2')).toBe(true);
    const out = serializeDeck(model);
    expect(out).not.toContain('data-eid="s2"');
    expect(out).toContain(S1);
    expect(out).toContain(S3);
  });

  it('removes the empty wrapper when deleting the last vertical child', () => {
    const model = parseDeck(DECK);
    deleteSlide(model, 's3a');
    deleteSlide(model, 's3b');
    const out = serializeDeck(model);
    // Both verticals gone AND the now-empty stack wrapper s3 is removed.
    expect(out).not.toContain('data-eid="s3a"');
    expect(out).not.toContain('data-eid="s3b"');
    expect(out).not.toContain('data-eid="s3"');
    expect(topLevelSlides(model).map((s) => getAttribute(s, 'data-eid'))).toEqual(['s1', 's2']);
  });

  it('returns false for an unknown eid', () => {
    const model = parseDeck(DECK);
    expect(deleteSlide(model, 'nope')).toBe(false);
  });
});

describe('moveSlide (P6-4)', () => {
  it('reorders top-level slides', () => {
    const model = parseDeck(DECK);
    expect(moveSlide(model, 0, 1)).toBe(true); // s1 → index 1 of [s2,s3]
    const out = serializeDeck(model);
    expect(eidOrder(out, ['s1', 's2', 's3'])).toEqual(['s2', 's1', 's3']);
    // s2 was not the moved element → byte-stable.
    expect(out).toContain(S2);
  });

  it('rejects an out-of-range index', () => {
    const model = parseDeck(DECK);
    expect(moveSlide(model, 9, 0)).toBe(false);
  });
});

describe('moveVerticalSlide (P6-5)', () => {
  it('reorders within a stack', () => {
    const model = parseDeck(DECK);
    expect(moveVerticalSlide(model, 's3', 0, 1)).toBe(true);
    const out = serializeDeck(model);
    expect(eidOrder(out, ['s3a', 's3b'])).toEqual(['s3b', 's3a']);
  });
});

describe('nestSlide (P6-5)', () => {
  it('nests a simple slide under the previous one, wrapping its content', () => {
    const model = parseDeck(DECK);
    const nested = nestSlide(model, 's2');
    expect(nested).not.toBeNull();

    // s1 is now a vertical stack: [wrapped-One, s2].
    const reparsed = parseDeck(serializeDeck(model));
    const top = topLevelSlides(reparsed);
    expect(top.map((s) => getAttribute(s, 'data-eid'))).toEqual(['s1', 's3']);
    expect(isVerticalStack(top[0])).toBe(true);
    const verts = verticalChildren(top[0]);
    // First vertical is the wrapped original content; second is s2.
    expect(getAttribute(verts[1], 'data-eid')).toBe('s2');
    expect(serializeDeck({ nodes: [verts[0]] })).toContain('<h1>One</h1>');
  });

  it('appends to an existing stack', () => {
    const model = parseDeck(DECK);
    // Move s2 to be just before the stack, then nest s3's... simpler: nest s3
    // under s2? s3 is a stack; nesting it under s2 appends the stack as a child.
    // Instead test the common path: add a slide then nest it under the stack.
    addSlide(model); // appended after s3
    stampEids(model);
    const newEid = getAttribute(topLevelSlides(model)[3], 'data-eid')!;
    const nested = nestSlide(model, newEid);
    expect(nested).not.toBeNull();
    const top = topLevelSlides(model);
    // s3 (already a stack) gains a third vertical child.
    expect(verticalChildren(top[2])).toHaveLength(3);
  });

  it('returns null for the first slide (no previous sibling)', () => {
    const model = parseDeck(DECK);
    expect(nestSlide(model, 's1')).toBeNull();
  });
});

describe('promoteSlide (P6-5)', () => {
  it('promotes a vertical slide to top-level after its stack', () => {
    const model = parseDeck(DECK);
    const promoted = promoteSlide(model, 's3a');
    expect(promoted).not.toBeNull();
    const out = serializeDeck(model);
    expect(eidOrder(out, ['s1', 's2', 's3', 's3a'])).toEqual(['s1', 's2', 's3', 's3a']);
    // s3 stack keeps its remaining child s3b.
    const top = topLevelSlides(parseDeck(out));
    const stack = top.find((s) => getAttribute(s, 'data-eid') === 's3')!;
    expect(verticalChildren(stack).map((s) => getAttribute(s, 'data-eid'))).toEqual(['s3b']);
  });

  it('removes the wrapper when the stack is emptied', () => {
    const model = parseDeck(DECK);
    promoteSlide(model, 's3a');
    promoteSlide(model, 's3b');
    const eids = topLevelSlides(model).map((s) => getAttribute(s, 'data-eid'));
    expect(eids).not.toContain('s3');
    expect(eids).toContain('s3a');
    expect(eids).toContain('s3b');
  });

  it('returns null when the eid is not a vertical slide', () => {
    const model = parseDeck(DECK);
    expect(promoteSlide(model, 's1')).toBeNull();
  });
});

describe('setSlideHidden (P6-6)', () => {
  it('sets and clears data-visibility="hidden"', () => {
    const model = parseDeck(DECK);
    expect(setSlideHidden(model, 's2', true)).toBe(true);
    let out = serializeDeck(model);
    expect(out).toContain('data-visibility="hidden"');
    expect(buildSlideTree(model)[1].hidden).toBe(true);

    expect(setSlideHidden(model, 's2', false)).toBe(true);
    out = serializeDeck(model);
    expect(out).not.toContain('data-visibility="hidden"');
    // Back to byte-stable original for s2.
    expect(out).toContain(S2);
  });
});

describe('buildThumbnailSrcdoc (P6-2)', () => {
  it('embeds the slide markup with deck-local stylesheet URLs', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    expect(doc).toContain('<base href="/decks/My%20Deck/">');
    expect(doc).toContain('assets/vendor/reveal/reveal.css');
    expect(doc).toContain('<h1>One</h1>');
    // No external URLs (offline-first, spec 12).
    expect(doc).not.toMatch(/https?:\/\//);
  });
});
