/**
 * slides.test.ts — Pure slide-management model ops (P6, spec 06).
 *
 * Verifies correctness of add / duplicate / delete / move / nest / promote / hide
 * AND the byte-stable round-trip invariant (spec 12 #4): every untouched sibling
 * slide serializes verbatim after an operation.
 */

import { describe, it, expect } from 'vitest';
import { parseDeck, serializeDeck, stampEids, getAttribute } from '$lib/model';
import {
  addSlide,
  duplicateSlide,
  deleteSlide,
  moveSlide,
  moveVerticalSlide,
  nestSlide,
  promoteSlide,
  setSlideHidden,
  topLevelSlides,
  verticalChildren,
  isVerticalStack,
  buildSlideTree,
  parsePresetSection,
  addSlideFromLayout,
  changeSlideLayout,
} from './slides';
import { buildThumbnailSrcdoc } from './thumbnail';

// Single-line slides keep substring byte-stability checks trivial. Whitespace
// between sections is a single '\n'.
const DECK = `<!doctype html>
<html>
<body>
<div class="reveal">
<div class="slides">
<section data-eid="s1" data-id="a"><h1>One</h1></section>
<section data-eid="s2"><h2>Two</h2></section>
<section data-eid="s3"><section data-eid="s3a"><p>3a</p></section><section data-eid="s3b"><p>3b</p></section></section>
</div>
</div>
</body>
</html>`;

const S1 = '<section data-eid="s1" data-id="a"><h1>One</h1></section>';
const S2 = '<section data-eid="s2"><h2>Two</h2></section>';
const S3 =
  '<section data-eid="s3"><section data-eid="s3a"><p>3a</p></section><section data-eid="s3b"><p>3b</p></section></section>';

/** Order of element eids inside the output, by source position. */
function eidOrder(html: string, eids: string[]): string[] {
  return [...eids]
    .map((eid) => ({ eid, at: html.indexOf(`data-eid="${eid}"`) }))
    .filter((e) => e.at >= 0)
    .sort((a, b) => a.at - b.at)
    .map((e) => e.eid);
}

describe('fixture sanity', () => {
  it('round-trips byte-for-byte unedited', () => {
    expect(serializeDeck(parseDeck(DECK))).toBe(DECK);
  });

  it('buildSlideTree reflects the 2D structure', () => {
    const tree = buildSlideTree(parseDeck(DECK));
    expect(tree.map((t) => t.eid)).toEqual(['s1', 's2', 's3']);
    expect(tree[0].verticals).toHaveLength(0);
    expect(tree[2].verticals.map((v) => v.eid)).toEqual(['s3a', 's3b']);
    expect(tree[2].hidden).toBe(false);
  });
});

describe('addSlide (P6-3)', () => {
  it('appends a starter section and leaves siblings byte-stable', () => {
    const model = parseDeck(DECK);
    const section = addSlide(model);
    expect(section).not.toBeNull();
    expect(getAttribute(section!, 'data-lay')).toBe('stack');
    const out = serializeDeck(model);
    expect(out).toContain('<section data-lay="stack"><h2>New slide</h2></section>');
    // Untouched slides serialize verbatim.
    expect(out).toContain(S1);
    expect(out).toContain(S2);
    expect(out).toContain(S3);
    // New slide is last.
    expect(topLevelSlides(model)).toHaveLength(4);
  });

  it('inserts after the given slide', () => {
    const model = parseDeck(DECK);
    addSlide(model, 's1');
    const out = serializeDeck(model);
    // New (unstamped) section lands between s1 and s2.
    const at1 = out.indexOf('data-eid="s1"');
    const atNew = out.indexOf('data-lay="stack"');
    const at2 = out.indexOf('data-eid="s2"');
    expect(at1).toBeLessThan(atNew);
    expect(atNew).toBeLessThan(at2);
  });

  it('returns null when there is no slides container', () => {
    const model = parseDeck('<div><p>no reveal here</p></div>');
    expect(addSlide(model)).toBeNull();
  });
});

describe('duplicateSlide (P6-3 / spec 07 pairing)', () => {
  it('clones after the original, strips data-eid, preserves data-id', () => {
    const model = parseDeck(DECK);
    const clone = duplicateSlide(model, 's1');
    expect(clone).not.toBeNull();
    // The clone has NO data-eid yet (regenerated by the caller's stampEids)…
    expect(getAttribute(clone!, 'data-eid')).toBeNull();
    // …but keeps data-id so reveal auto-animate can pair the two slides.
    expect(getAttribute(clone!, 'data-id')).toBe('a');

    const out = serializeDeck(model);
    expect(out).toContain('<section data-id="a"><h1>One</h1></section>'); // the copy
    expect(out).toContain(S1); // original untouched
    expect(out).toContain(S2);
  });

  it('regenerates a unique eid after stampEids', () => {
    const model = parseDeck(DECK);
    const clone = duplicateSlide(model, 's1')!;
    stampEids(model);
    const eid = getAttribute(clone, 'data-eid');
    expect(eid).not.toBeNull();
    expect(['s1', 's2', 's3', 's3a', 's3b']).not.toContain(eid);
  });

  it('duplicates a vertical slide in place', () => {
    const model = parseDeck(DECK);
    const clone = duplicateSlide(model, 's3a');
    expect(clone).not.toBeNull();
    // Copy sits inside the stack, right after s3a.
    expect(verticalChildren(topLevelSlides(model)[2])).toHaveLength(3);
  });
});

describe('deleteSlide (P6-3)', () => {
  it('removes the slide and keeps siblings byte-stable', () => {
    const model = parseDeck(DECK);
    expect(deleteSlide(model, 's2')).toBe(true);
    const out = serializeDeck(model);
    expect(out).not.toContain('data-eid="s2"');
    expect(out).toContain(S1);
    expect(out).toContain(S3);
  });

  it('removes the empty wrapper when deleting the last vertical child', () => {
    const model = parseDeck(DECK);
    deleteSlide(model, 's3a');
    deleteSlide(model, 's3b');
    const out = serializeDeck(model);
    // Both verticals gone AND the now-empty stack wrapper s3 is removed.
    expect(out).not.toContain('data-eid="s3a"');
    expect(out).not.toContain('data-eid="s3b"');
    expect(out).not.toContain('data-eid="s3"');
    expect(topLevelSlides(model).map((s) => getAttribute(s, 'data-eid'))).toEqual(['s1', 's2']);
  });

  it('returns false for an unknown eid', () => {
    const model = parseDeck(DECK);
    expect(deleteSlide(model, 'nope')).toBe(false);
  });
});

describe('moveSlide (P6-4)', () => {
  it('reorders top-level slides', () => {
    const model = parseDeck(DECK);
    expect(moveSlide(model, 0, 1)).toBe(true); // s1 → index 1 of [s2,s3]
    const out = serializeDeck(model);
    expect(eidOrder(out, ['s1', 's2', 's3'])).toEqual(['s2', 's1', 's3']);
    // s2 was not the moved element → byte-stable.
    expect(out).toContain(S2);
  });

  it('rejects an out-of-range index', () => {
    const model = parseDeck(DECK);
    expect(moveSlide(model, 9, 0)).toBe(false);
  });
});

describe('moveVerticalSlide (P6-5)', () => {
  it('reorders within a stack', () => {
    const model = parseDeck(DECK);
    expect(moveVerticalSlide(model, 's3', 0, 1)).toBe(true);
    const out = serializeDeck(model);
    expect(eidOrder(out, ['s3a', 's3b'])).toEqual(['s3b', 's3a']);
  });
});

describe('nestSlide (P6-5)', () => {
  it('nests a simple slide under the previous one, wrapping its content', () => {
    const model = parseDeck(DECK);
    const nested = nestSlide(model, 's2');
    expect(nested).not.toBeNull();

    // s1 is now a vertical stack: [wrapped-One, s2].
    const reparsed = parseDeck(serializeDeck(model));
    const top = topLevelSlides(reparsed);
    expect(top.map((s) => getAttribute(s, 'data-eid'))).toEqual(['s1', 's3']);
    expect(isVerticalStack(top[0])).toBe(true);
    const verts = verticalChildren(top[0]);
    // First vertical is the wrapped original content; second is s2.
    expect(getAttribute(verts[1], 'data-eid')).toBe('s2');
    expect(serializeDeck({ nodes: [verts[0]] })).toContain('<h1>One</h1>');
  });

  it('appends to an existing stack', () => {
    const model = parseDeck(DECK);
    // Move s2 to be just before the stack, then nest s3's... simpler: nest s3
    // under s2? s3 is a stack; nesting it under s2 appends the stack as a child.
    // Instead test the common path: add a slide then nest it under the stack.
    addSlide(model); // appended after s3
    stampEids(model);
    const newEid = getAttribute(topLevelSlides(model)[3], 'data-eid')!;
    const nested = nestSlide(model, newEid);
    expect(nested).not.toBeNull();
    const top = topLevelSlides(model);
    // s3 (already a stack) gains a third vertical child.
    expect(verticalChildren(top[2])).toHaveLength(3);
  });

  it('returns null for the first slide (no previous sibling)', () => {
    const model = parseDeck(DECK);
    expect(nestSlide(model, 's1')).toBeNull();
  });
});

describe('promoteSlide (P6-5)', () => {
  it('promotes a vertical slide to top-level after its stack', () => {
    const model = parseDeck(DECK);
    const promoted = promoteSlide(model, 's3a');
    expect(promoted).not.toBeNull();
    const out = serializeDeck(model);
    expect(eidOrder(out, ['s1', 's2', 's3', 's3a'])).toEqual(['s1', 's2', 's3', 's3a']);
    // s3 stack keeps its remaining child s3b.
    const top = topLevelSlides(parseDeck(out));
    const stack = top.find((s) => getAttribute(s, 'data-eid') === 's3')!;
    expect(verticalChildren(stack).map((s) => getAttribute(s, 'data-eid'))).toEqual(['s3b']);
  });

  it('removes the wrapper when the stack is emptied', () => {
    const model = parseDeck(DECK);
    promoteSlide(model, 's3a');
    promoteSlide(model, 's3b');
    const eids = topLevelSlides(model).map((s) => getAttribute(s, 'data-eid'));
    expect(eids).not.toContain('s3');
    expect(eids).toContain('s3a');
    expect(eids).toContain('s3b');
  });

  it('returns null when the eid is not a vertical slide', () => {
    const model = parseDeck(DECK);
    expect(promoteSlide(model, 's1')).toBeNull();
  });
});

describe('setSlideHidden (P6-6)', () => {
  it('sets and clears data-visibility="hidden"', () => {
    const model = parseDeck(DECK);
    expect(setSlideHidden(model, 's2', true)).toBe(true);
    let out = serializeDeck(model);
    expect(out).toContain('data-visibility="hidden"');
    expect(buildSlideTree(model)[1].hidden).toBe(true);

    expect(setSlideHidden(model, 's2', false)).toBe(true);
    out = serializeDeck(model);
    expect(out).not.toContain('data-visibility="hidden"');
    // Back to byte-stable original for s2.
    expect(out).toContain(S2);
  });
});

// ─── P14: layout presets (new-from-layout / change-layout) ───────────────────

// A representative preset: a section with a nested data-slot="content" container
// and starter prompt content (mirrors vendor/layouts/two-content.html).
const PRESET_TWO_CONTENT = `<section data-layout="two-content">
  <div data-lay="stack" data-gap="32">
    <h2>Click to add title</h2>
    <div data-lay="row" data-gap="48" data-slot="content">
      <div data-lay="stack" data-grow="1"><p>Click to add text</p></div>
      <div data-lay="stack" data-grow="1"><p>Click to add text</p></div>
    </div>
  </div>
</section>`;

const PRESET_TITLE_BODY = `<section data-layout="title-body">
  <div data-lay="stack" data-gap="32" data-slot="content">
    <h2>Click to add title</h2>
    <p>Click to add body text</p>
  </div>
</section>`;

/** Count occurrences of a data-eid value in an HTML string. */
function eidCount(html: string, eid: string): number {
  return [...html.matchAll(/data-eid="([^"]+)"/g)].filter((m) => m[1] === eid).length;
}

/** All data-eids in an HTML string (document order). */
function allEids(html: string): string[] {
  return [...html.matchAll(/data-eid="([^"]+)"/g)].map((m) => m[1]);
}

describe('parsePresetSection (P14)', () => {
  it('extracts the first <section> subtree carrying its data-layout marker', () => {
    const section = parsePresetSection(PRESET_TITLE_BODY);
    expect(section).not.toBeNull();
    expect(section!.tagName.toLowerCase()).toBe('section');
    expect(getAttribute(section!, 'data-layout')).toBe('title-body');
  });

  it('returns null for a snippet with no section', () => {
    expect(parsePresetSection('<div>nope</div>')).toBeNull();
  });
});

describe('addSlideFromLayout (P14-3)', () => {
  it('inserts the preset structure + starter content after the target slide', () => {
    const model = parseDeck(DECK);
    const section = addSlideFromLayout(model, PRESET_TITLE_BODY, 's1');
    expect(section).not.toBeNull();
    // No stampEids here: the bare insert keeps every sibling byte-stable.
    const out = serializeDeck(model);

    // Preset structure + starter prompts are present.
    expect(out).toContain('data-layout="title-body"');
    expect(out).toContain('data-slot="content"');
    expect(out).toContain('Click to add title');
    expect(out).toContain('Click to add body text');
    // Inserted immediately after s1, before s2.
    const order = eidOrder(out, ['s1', 's2']);
    expect(order).toEqual(['s1', 's2']);
    const at = out.indexOf('data-layout="title-body"');
    expect(at).toBeGreaterThan(out.indexOf(S1));
    expect(at).toBeLessThan(out.indexOf(S2));
    // Untouched siblings round-trip verbatim (spec 12 #4).
    expect(out).toContain(S1);
    expect(out).toContain(S2);
    expect(out).toContain(S3);
  });

  it('appends to the end when afterEid is omitted', () => {
    const model = parseDeck(DECK);
    addSlideFromLayout(model, PRESET_TITLE_BODY);
    stampEids(model);
    const out = serializeDeck(model);
    expect(out.indexOf('data-layout="title-body"')).toBeGreaterThan(out.indexOf(S3));
  });

  it('stamps fresh, unique data-eids on every managed element of the new slide', () => {
    const model = parseDeck(DECK);
    const section = addSlideFromLayout(model, PRESET_TWO_CONTENT)!;
    stampEids(model);
    const out = serializeDeck(model);

    // The new section + its containers + leaves all carry an eid…
    const newEid = getAttribute(section, 'data-eid');
    expect(newEid).not.toBeNull();
    // …and every eid in the whole deck is unique.
    const eids = allEids(out);
    expect(new Set(eids).size).toBe(eids.length);
    // The preset itself shipped with no eids, so the new slide's eids are fresh
    // (none collide with the fixture's s1/s2/s3).
    expect(eids.filter((e) => e === 's1')).toHaveLength(1);
  });
});

describe('changeSlideLayout (P14-4)', () => {
  // A slide with MULTIPLE content leaves spread across layout scaffolding.
  const RICH = `<!doctype html>
<html>
<body>
<div class="reveal">
<div class="slides">
<section data-eid="s1"><h1 data-eid="e1">One</h1></section>
<section data-eid="sx" data-transition="zoom"><div data-eid="c0" data-lay="stack"><h2 data-eid="h">Title</h2><div data-eid="c1" data-lay="row"><p data-eid="p1">Left</p><ul data-eid="u1"><li data-eid="li1">a</li></ul></div><img data-eid="im1" src="x.png"></div></section>
<section data-eid="s3"><h2 data-eid="e3">Three</h2></section>
</div>
</div>
</body>
</html>`;

  it('moves ALL existing content leaves into the new content slot (nothing lost)', () => {
    const model = parseDeck(RICH);
    const section = changeSlideLayout(model, 'sx', PRESET_TITLE_BODY);
    expect(section).not.toBeNull();
    stampEids(model);
    const out = serializeDeck(model);

    // The new layout marker is applied; the section keeps its identity + attrs.
    expect(getAttribute(section!, 'data-layout')).toBe('title-body');
    expect(out).toContain('data-eid="sx"');
    expect(out).toContain('data-transition="zoom"');

    // Every authored leaf survives (nothing dropped).
    for (const eid of ['h', 'p1', 'u1', 'li1', 'im1']) {
      expect(eidCount(out, eid)).toBe(1);
    }
    // …and all of them now live inside the data-slot="content" container.
    const slotStart = out.indexOf('data-slot="content"');
    expect(slotStart).toBeGreaterThan(-1);
    const sectionEnd = out.indexOf('</section>', slotStart);
    const slotRegion = out.slice(slotStart, sectionEnd);
    for (const eid of ['h', 'p1', 'u1', 'li1', 'im1']) {
      expect(slotRegion).toContain(`data-eid="${eid}"`);
    }
    // The preset's starter prompts in the content slot were replaced.
    expect(slotRegion).not.toContain('Click to add body text');

    // Position is preserved (sx still between s1 and s3) and siblings byte-stable.
    expect(eidOrder(out, ['s1', 'sx', 's3'])).toEqual(['s1', 'sx', 's3']);
    expect(out).toContain('<section data-eid="s1"><h1 data-eid="e1">One</h1></section>');
    expect(out).toContain('<section data-eid="s3"><h2 data-eid="e3">Three</h2></section>');
  });

  it('keeps the preset prompts when the slide has no content to move', () => {
    const empty = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1"><div data-eid="c" data-lay="stack"></div></section>
</div></div></body></html>`;
    const model = parseDeck(empty);
    changeSlideLayout(model, 's1', PRESET_TITLE_BODY);
    stampEids(model);
    const out = serializeDeck(model);
    expect(out).toContain('Click to add body text');
  });

  it('returns null for an unknown section eid', () => {
    const model = parseDeck(DECK);
    expect(changeSlideLayout(model, 'nope', PRESET_TITLE_BODY)).toBeNull();
  });
});

describe('buildThumbnailSrcdoc (P6-2)', () => {
  it('embeds the slide markup with deck-local stylesheet URLs', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    expect(doc).toContain('<base href="/decks/My%20Deck/">');
    expect(doc).toContain('assets/vendor/reveal/reveal.css');
    expect(doc).toContain('<h1>One</h1>');
    // No external URLs (offline-first, spec 12).
    expect(doc).not.toMatch(/https?:\/\//);
  });

  it('uses the theme passed via opts (non-black theme link present)', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1, { theme: 'moon' });
    expect(doc).toContain('assets/vendor/reveal/theme/moon.css');
    expect(doc).not.toContain('assets/vendor/reveal/theme/black.css');
  });

  it('falls back to the black theme when no opts.theme is provided', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    expect(doc).toContain('assets/vendor/reveal/theme/black.css');
  });

  it('links slides-slide-themes.css for per-slide data-theme overrides', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    expect(doc).toContain('assets/vendor/slides-slide-themes.css');
  });

  it('forces .fragment elements visible so all content shows in the thumbnail', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    expect(doc).toContain('.fragment');
    expect(doc).toContain('opacity: 1 !important');
    expect(doc).toContain('visibility: visible !important');
  });

  it('substitutes a static placeholder for a <canvas data-chart> (P17-16)', () => {
    const DECK_WITH_CHART = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1"><canvas data-eid="c1" data-chart="bar" width="600" height="400" data-chart-data='{"type":"bar","data":{"labels":["A"],"datasets":[{"data":[1]}]}}'></canvas></section>
</div></div></body></html>`;
    const model = parseDeck(DECK_WITH_CHART);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    // Charts are JS-driven; the script-free thumbnail must NOT keep the <canvas>.
    expect(doc).not.toContain('<canvas');
    // It shows the static placeholder + the chart type caption instead.
    expect(doc).toContain('sb-chart-placeholder');
    expect(doc).toContain('bar chart');
    // Still offline (no external URLs).
    expect(doc).not.toMatch(/https?:\/\//);
  });

  it('applies data-background-color as the section background in the thumbnail', () => {
    const DECK_WITH_BG = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1" data-background-color="#ff0000"><h1>Red BG</h1></section>
</div></div></body></html>`;
    const model = parseDeck(DECK_WITH_BG);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    expect(doc).toContain('background-color: #ff0000 !important');
  });

  it('does not add a background-color rule when the section has none', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    // The rule should be absent (empty string injection).
    expect(doc).not.toContain('background-color:');
  });

  it('contains no external (http/https) URLs — offline-first', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1, { theme: 'white' });
    expect(doc).not.toMatch(/https?:\/\//);
  });

  describe('slide background types (P16-4)', () => {
    it('renders data-background-image as background-image CSS with default size/position/repeat', () => {
      const DECK_BG_IMG = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1" data-background-image="assets/bg.jpg"><h1>Image BG</h1></section>
</div></div></body></html>`;
      const model = parseDeck(DECK_BG_IMG);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      expect(doc).toContain("background-image: url('assets/bg.jpg')");
      expect(doc).toContain('background-size: cover');
      expect(doc).toContain('background-position: center');
      expect(doc).toContain('background-repeat: no-repeat');
      // Offline-first: no external URLs.
      expect(doc).not.toMatch(/https?:\/\//);
    });

    it('honours explicit data-background-size/-position/-repeat overrides', () => {
      const DECK_BG_IMG = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1" data-background-image="assets/tile.png" data-background-size="contain" data-background-position="top left" data-background-repeat="repeat"><h1>Tiled</h1></section>
</div></div></body></html>`;
      const model = parseDeck(DECK_BG_IMG);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      expect(doc).toContain("background-image: url('assets/tile.png')");
      expect(doc).toContain('background-size: contain');
      expect(doc).toContain('background-position: top left');
      expect(doc).toContain('background-repeat: repeat');
      expect(doc).not.toMatch(/https?:\/\//);
    });

    it('renders data-background-opacity via a ::before pseudo-element so image opacity does not bleed onto slide text', () => {
      const DECK_BG_OPACITY = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1" data-background-image="assets/bg.jpg" data-background-opacity="0.4"><h1>Semi-transparent BG</h1></section>
</div></div></body></html>`;
      const model = parseDeck(DECK_BG_OPACITY);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      // Image is placed in ::before (not inline on the section).
      expect(doc).toContain('::before');
      expect(doc).toContain("url('assets/bg.jpg')");
      expect(doc).toContain('opacity: 0.4');
      // No inline background-image on the section itself.
      expect(doc).not.toContain("background-image: url('assets/bg.jpg') !important");
      expect(doc).not.toMatch(/https?:\/\//);
    });

    it('silently drops external data-background-image URLs — no CSS url() emitted (offline-first)', () => {
      const DECK_EXT_IMG = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1" data-background-image="https://example.com/bg.jpg"><h1>Ext</h1></section>
</div></div></body></html>`;
      const model = parseDeck(DECK_EXT_IMG);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      // The external URL must NOT appear inside a CSS url() expression — that
      // would cause the browser to load the external resource. The attribute
      // value may still appear in serialized HTML (harmless; browsers only
      // fetch URLs in src/href/CSS, not arbitrary data-* attributes).
      expect(doc).not.toMatch(/url\(['"]?https?:\/\//);
      // No background-image CSS rule is injected for external paths.
      expect(doc).not.toContain('background-image: url(');
    });

    it('renders data-background-gradient as a CSS background shorthand', () => {
      const DECK_BG_GRAD = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1" data-background-gradient="linear-gradient(135deg, #667eea 0%, #764ba2 100%)"><h1>Gradient BG</h1></section>
</div></div></body></html>`;
      const model = parseDeck(DECK_BG_GRAD);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      expect(doc).toContain('background: linear-gradient(135deg, #667eea 0%, #764ba2 100%)');
      expect(doc).not.toMatch(/https?:\/\//);
    });

    it('renders a neutral dark placeholder for data-background-video — no <video> element, play glyph via ::after', () => {
      const DECK_BG_VIDEO = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="s1" data-background-video="assets/demo.mp4"><h1>Video BG</h1></section>
</div></div></body></html>`;
      const model = parseDeck(DECK_BG_VIDEO);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      // Dark background applied to the section.
      expect(doc).toContain('background: #1a1a2e !important');
      // Play-button glyph via ::after (no scripting required).
      expect(doc).toContain('::after');
      // The video src is NOT echoed into a <video> element (no playback).
      expect(doc).not.toContain('<video');
      // No external URLs.
      expect(doc).not.toMatch(/https?:\/\//);
    });
  });

  it('does not force flex on every section (lets data-lay display win)', () => {
    const model = parseDeck(DECK);
    const s1 = topLevelSlides(model)[0];
    const doc = buildThumbnailSrcdoc('My Deck', s1);
    // The flex-everything override (the old bug) must be gone.
    expect(doc).not.toContain('display: flex !important');
    // Each layout type's real display is re-asserted at the section level.
    expect(doc).toContain('.reveal .slides > section[data-lay="grid"]   { display: grid; }');
    expect(doc).toContain('.reveal .slides > section[data-lay="row"]    { display: flex; flex-direction: row; }');
    expect(doc).toContain('.reveal .slides > section[data-lay="stack"]  { display: flex; flex-direction: column; }');
    // Plain (no data-lay) sections still centre vertically.
    expect(doc).toContain('.reveal .slides > section:not([data-lay])');
  });

  describe('numeric layout is resolved statically (P12 wiring)', () => {
    it('renders grid-template-columns inline for a grid section', () => {
      const GRID = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="g1" data-lay="grid" data-cols="3" data-gap="24"><div>a</div><div>b</div><div>c</div></section>
</div></div></body></html>`;
      const model = parseDeck(GRID);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      // Numeric layout resolved to inline style (mirrors slides-layout-init.js).
      expect(doc).toContain('grid-template-columns: repeat(3, 1fr)');
      // Gap is applied (logical px).
      expect(doc).toContain('gap: 24px');
      // No external URLs (offline-first, spec 12).
      expect(doc).not.toMatch(/https?:\/\//);
    });

    it('renders left/top/width/height inline for a free-positioned element', () => {
      const FREE = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="f1"><div data-free data-x="120" data-y="80" data-w="400" data-h="300" data-rot="15">box</div></section>
</div></div></body></html>`;
      const model = parseDeck(FREE);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      expect(doc).toContain('left: 120px');
      expect(doc).toContain('top: 80px');
      expect(doc).toContain('width: 400px');
      expect(doc).toContain('height: 300px');
      expect(doc).toContain('transform: rotate(15deg)');
      expect(doc).not.toMatch(/https?:\/\//);
    });

    it('resolves flex grow/basis on row children', () => {
      const ROW = `<!doctype html>
<html><body><div class="reveal"><div class="slides">
<section data-eid="r1" data-lay="row" data-gap="40"><div data-grow="1" data-basis="200">l</div><div data-basis="50%">r</div></section>
</div></div></body></html>`;
      const model = parseDeck(ROW);
      const s1 = topLevelSlides(model)[0];
      const doc = buildThumbnailSrcdoc('My Deck', s1);
      expect(doc).toContain('flex-grow: 1');
      expect(doc).toContain('flex-basis: 200px');
      expect(doc).toContain('flex-basis: 50%');
      expect(doc).toContain('gap: 40px');
    });
  });
});
