/**
 * e2e/global-setup.ts — Playwright global setup for slides-builder.
 *
 * Runs once before all specs. Responsibilities:
 *  1. Locate the pre-built `slides` binary (must already be compiled).
 *  2. Create a temp workspace directory.
 *  3. Write a config.toml to that workspace so the server uses TEST_PORT.
 *  4. Scaffold a test deck: `./slides new smoke-deck`.
 *  5. Start `./slides` (serving from the temp workspace) and wait until
 *     GET /health returns 200.
 *  6. Write the temp-dir path and PID to a shared-state file so
 *     global-teardown.ts can clean up.
 *
 * The binary is NOT rebuilt here — the npm script `test:e2e` runs
 * `go build` first so by the time this runs the binary is fresh.
 */

import { spawn } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ESM: reproduce __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ---------------------------------------------------------------------------
// Constants shared between setup and teardown via a state file.
// The state file lives next to this file so it's easy to find.
// ---------------------------------------------------------------------------

/** Where to write the runtime state (PID + tmpDir) for teardown. */
export const STATE_FILE = join(__dirname, '.e2e-state.json');

/** The deck name scaffolded during setup (used by specs). */
export const SMOKE_DECK = 'smoke-deck';

/** The port the test server listens on. */
export const TEST_PORT = parseInt(process.env.TEST_PORT ?? '19999', 10);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Poll GET /health until it returns 200 or the timeout expires. */
async function waitForServer(port: number, timeoutMs = 15_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  const url = `http://localhost:${port}/health`;

  while (Date.now() < deadline) {
    try {
      const res = await fetch(url);
      if (res.ok) return;
    } catch {
      // server not up yet
    }
    await new Promise((r) => setTimeout(r, 200));
  }
  throw new Error(`Server on port ${port} did not become healthy within ${timeoutMs}ms`);
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

export default async function globalSetup(): Promise<void> {
  // Repo root is two levels above web/ (web/e2e/ → web/ → repo-root)
  const repoRoot = resolve(__dirname, '..', '..');
  const binaryPath = join(repoRoot, 'slides');

  if (!existsSync(binaryPath)) {
    throw new Error(
      `slides binary not found at ${binaryPath}.\n` +
        'Run `go build -o slides ./cmd/slides` from the repo root first,\n' +
        'or use `npm run test:e2e` which builds it automatically.',
    );
  }

  // Create a temp workspace directory so we never touch the real decks/.
  const tmpDir = await mkdtemp(join(tmpdir(), 'slides-e2e-'));

  // Write config.toml pointing at the test port.
  writeFileSync(
    join(tmpDir, 'config.toml'),
    `# Auto-generated by Playwright global setup. Do not edit.\nport = ${TEST_PORT}\n`,
  );

  // Scaffold the test deck.
  // `slides new <name>` creates decks/<name>/{deck.html,custom.css,assets/}.
  // The binary uses CWD as workspace root, so we pass cwd: tmpDir.
  await new Promise<void>((resolve, reject) => {
    const proc = spawn(binaryPath, ['new', SMOKE_DECK], {
      cwd: tmpDir,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stderr = '';
    proc.stderr?.on('data', (d: Buffer) => (stderr += d.toString()));
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`slides new failed (exit ${code}):\n${stderr}`));
    });
  });

  // Start the server (non-blocking). cwd=tmpDir means the workspace is the
  // temp directory we prepared.
  const server = spawn(binaryPath, ['serve'], {
    cwd: tmpDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    // Detach is intentionally NOT set — teardown kills by PID within the
    // same process group so the process tree is cleaned up automatically.
  });

  // Surface server stderr to the Playwright reporter if anything goes wrong.
  server.stderr?.on('data', (d: Buffer) => process.stderr.write(`[slides-server] ${d}`));
  server.stdout?.on('data', (d: Buffer) => process.stdout.write(`[slides-server] ${d}`));

  server.on('error', (err) => {
    throw new Error(`Failed to start slides server: ${err.message}`);
  });

  // Persist PID + tmpDir so teardown can kill the process and remove the dir.
  writeFileSync(
    STATE_FILE,
    JSON.stringify({ pid: server.pid, tmpDir }, null, 2),
  );

  // Wait until the server is healthy before handing control to the specs.
  await waitForServer(TEST_PORT);

  console.log(
    `[e2e setup] Server started (pid=${server.pid}) on port ${TEST_PORT} ` +
      `with workspace at ${tmpDir} and deck "${SMOKE_DECK}".`,
  );
}
