/**
 * e2e/global-setup.ts — Playwright global setup for decks.
 *
 * Runs once before all specs. Responsibilities:
 *  1. Locate the pre-built `decks` binary (must already be compiled).
 *  2. Create a temp workspace directory.
 *  3. Write a config.toml to that workspace so the server uses TEST_PORT.
 *  4. Scaffold the baseline deck: `decks --dir <tmp> new smoke-deck`. It exists so
 *     a cold `GET /` has a deck to open; specs that mutate a deck create their
 *     own with `createDeck()` (see fixtures.ts) rather than sharing this one.
 *  5. Start `decks --dir <tmp> serve` and wait until GET /health returns 200.
 *  6. Write the temp-dir path and PID to a shared-state file so
 *     global-teardown.ts can clean up.
 *
 * The binary is NOT rebuilt here — the npm script `test:e2e` runs
 * `go build` first so by the time this runs the binary is fresh.
 */

import { spawn } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SMOKE_DECK, STATE_FILE, TEST_PORT } from './constants.ts';

// ESM: reproduce __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Poll GET /health until it returns 200 or the timeout expires. */
async function waitForServer(port: number, timeoutMs = 15_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  const url = `http://localhost:${port}/health`;

  while (Date.now() < deadline) {
    try {
      const res = await fetch(url);
      if (res.ok) return;
    } catch {
      // server not up yet
    }
    await new Promise((r) => setTimeout(r, 200));
  }
  throw new Error(`Server on port ${port} did not become healthy within ${timeoutMs}ms`);
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

export default async function globalSetup(): Promise<void> {
  // Repo root is two levels above web/ (web/e2e/ → web/ → repo-root)
  const repoRoot = resolve(__dirname, '..', '..');
  const binaryPath = join(repoRoot, 'bin', 'decks');

  if (!existsSync(binaryPath)) {
    throw new Error(
      `decks binary not found at ${binaryPath}.\n` +
        'Run `go build -o bin/decks ./cmd/decks` from the repo root first,\n' +
        'or use `npm run test:e2e` which builds it automatically.',
    );
  }

  // Create a temp workspace directory so we never touch the real decks/.
  const tmpDir = await mkdtemp(join(tmpdir(), 'decks-e2e-'));

  // Write config.toml pointing at the test port.
  writeFileSync(
    join(tmpDir, 'config.toml'),
    `# Auto-generated by Playwright global setup. Do not edit.\nport = ${TEST_PORT}\n`,
  );

  // Scaffold the test deck.
  // `decks new <name>` creates decks/<name>/{deck.html,custom.css,assets/}.
  //
  // We pass `--dir tmpDir` rather than relying on cwd: the binary resolves its
  // workspace by walking up from the cwd looking for decks/, so a cwd-only setup
  // would silently adopt an ancestor workspace if one ever existed above the OS
  // temp dir. `--dir` pins it, and `new` initializes tmpDir since it has no decks/.
  await new Promise<void>((resolve, reject) => {
    const proc = spawn(binaryPath, ['--dir', tmpDir, 'new', SMOKE_DECK], {
      cwd: tmpDir,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stderr = '';
    proc.stderr?.on('data', (d: Buffer) => (stderr += d.toString()));
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`decks new failed (exit ${code}):\n${stderr}`));
    });
  });

  // Start the server (non-blocking), pinned to the temp workspace we just
  // initialized. It now has decks/, so `serve` resolves it as a real workspace.
  const server = spawn(binaryPath, ['--dir', tmpDir, 'serve'], {
    cwd: tmpDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    // Detach is intentionally NOT set — teardown kills by PID within the
    // same process group so the process tree is cleaned up automatically.
  });

  // Surface server stderr to the Playwright reporter if anything goes wrong.
  server.stderr?.on('data', (d: Buffer) => process.stderr.write(`[decks-server] ${d}`));
  server.stdout?.on('data', (d: Buffer) => process.stdout.write(`[decks-server] ${d}`));

  server.on('error', (err) => {
    throw new Error(`Failed to start decks server: ${err.message}`);
  });

  // Persist PID + tmpDir so teardown can kill the process and remove the dir.
  writeFileSync(
    STATE_FILE,
    JSON.stringify({ pid: server.pid, tmpDir }, null, 2),
  );

  // Wait until the server is healthy before handing control to the specs.
  await waitForServer(TEST_PORT);

  console.log(
    `[e2e setup] Server started (pid=${server.pid}) on port ${TEST_PORT} ` +
      `with workspace at ${tmpDir} and deck "${SMOKE_DECK}".`,
  );
}
